# Render Blueprint for RitKART E-commerce Application
services:
  # Backend Service (Java Spring Boot)
  - type: web
    name: ritkart-backend
    env: docker
    repo: https://github.com/MASTER-2222/ecom.git
    rootDir: backend
    dockerfilePath: ./Dockerfile
    plan: starter
    region: oregon
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: SERVER_PORT
        value: 8080
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: MONGODB_URI
        sync: false  # This will need to be set manually for security
      - key: MONGODB_DATABASE
        value: ritkart
      - key: JWT_SECRET
        sync: false  # This will need to be set manually for security
      - key: JWT_EXPIRATION
        value: 86400000
      - key: CORS_ALLOWED_ORIGINS
        fromService:
          type: web
          name: ritkart-frontend
          envVarKey: RENDER_EXTERNAL_URL
      - key: CLOUDINARY_CLOUD_NAME
        value: dv0lg87ib
      - key: CLOUDINARY_API_KEY
        value: 195345735854272
      - key: CLOUDINARY_API_SECRET
        sync: false  # This will need to be set manually for security
      - key: DEFAULT_ADMIN_EMAIL
        value: admin@ritkart.com
      - key: DEFAULT_ADMIN_PASSWORD
        sync: false  # This will need to be set manually for security
      - key: MAX_FILE_SIZE
        value: 10MB
      - key: LOG_LEVEL
        value: INFO

  # Frontend Service (Next.js Static Site)
  - type: web
    name: ritkart-frontend
    env: static
    repo: https://github.com/MASTER-2222/ecom.git
    rootDir: frontend2
    buildCommand: npm install && npm run build
    staticPublishPath: out
    plan: starter
    region: oregon
    envVars:
      - key: NEXT_PUBLIC_API_URL
        fromService:
          type: web
          name: ritkart-backend
          envVarKey: RENDER_EXTERNAL_URL
          property: url
          # Will automatically append /api to the backend URL
      - key: NEXT_PUBLIC_BACKEND_URL
        fromService:
          type: web
          name: ritkart-backend
          envVarKey: RENDER_EXTERNAL_URL
      - key: NEXT_PUBLIC_APP_NAME
        value: RitKART
      - key: NEXT_PUBLIC_ENVIRONMENT
        value: production
      - key: NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME
        value: dv0lg87ib
      - key: NEXT_PUBLIC_CLOUDINARY_API_KEY
        value: 195345735854272

databases: []
# Note: Using external MongoDB Atlas, so no database service needed