services:
  # Frontend Service
  - type: web
    name: ritkart-frontend
    env: static
    buildCommand: cd frontend && npm install --legacy-peer-deps && npm run build
    staticPublishPath: ./frontend/dist
    pullRequestPreviewsEnabled: false
    headers:
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: NPM_CONFIG_LEGACY_PEER_DEPS
        value: "true"

  # Backend Service  
  - type: web
    name: ritkart-backend
    env: java
    buildCommand: cd backend && mvn clean package -DskipTests
    startCommand: cd backend && java -jar target/ritkart-backend-1.0.0.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SERVER_PORT
        value: "8080"
      - key: MAVEN_OPTS
        value: "-Xmx1g"