# Render.com Deployment Configuration

# For Backend Service
name: ritkart-backend
type: web
plan: free
runtime: java
repo: https://github.com/MASTER-2222/ecom
branch: main
rootDir: backend
buildCommand: "./mvnw clean package -DskipTests"
startCommand: "java -jar target/ritkart-backend-1.0.0.jar"

# Environment Variables for Backend
MONGODB_URI: mongodb+srv://ritkart-admin:YOUR_PASSWORD@ritkart-cluster.xxxxx.mongodb.net/ritkart?retryWrites=true&w=majority
MONGODB_DATABASE: ritkart
JWT_SECRET: RitKART-Production-Secret-Key-2024-Ultra-Secure-256-Bit-HMAC-SHA
SERVER_PORT: 8080
CORS_ALLOWED_ORIGINS: https://ritkart-frontend.onrender.com
SPRING_PROFILES_ACTIVE: prod
DEFAULT_ADMIN_EMAIL: admin@ritkart.com
DEFAULT_ADMIN_PASSWORD: admin123

# Health Check
healthCheckPath: /api/actuator/health